webroot/common/ui/css/contrail.custom.css
webroot/common/ui/templates/core.common.tmpl
webroot/js/common/core.constants.js
webroot/js/common/core.utils.js
webroot/js/views/GridStackView.js
webroot/js/views/LineBarWithFocusChartView.js
webroot/js/views/LineWithFocusChartView.js
webroot/js/views/StackedBarChartWithFocusView.js

Change-Id: I293706899b73adbbfbdd68251ab5bd8119448e1e

gridstack & carousel changes integrated

---

webroot/common/ui/css/contrail.custom.css
webroot/js/views/StackedAreaChartView.js
webroot/js/views/ZoomScatterChartView.js

padding adjustments in charts
Change-Id: I7046c9a84cd4f7b0514acbc5e34cc817e5e7938e

carousel in config node, removed not data message in scatter chart

---

webroot/common/ui/css/contrail.custom.css
webroot/common/ui/templates/core.common.tmpl
webroot/js/views/StackedAreaChartView.js

- Made css changes to gridstack to show the border only on hover
Change-Id: Iaf20adf7abb324a9b7b9825c0f1b8c73b1ad045a

- StackdAreaChart made the height auto adjust to the parent

---

webroot/js/common/core.utils.js
webroot/js/models/ContrailConfigModel.js
webroot/js/views/ContrailView.js
webroot/js/views/tagsView.js

Change-Id: I6712b04532fb4ffd226c27bacb3f3b90abc7e479

 Tags view core changes

---

webroot/js/common/core.utils.js

Change-Id: I95f7c6c5d58e8c1898181661d91db65dd278bad0

  Changes to Tag - Added check before pushing the items to grid

---

webroot/js/models/ContrailConfigModel.js

Added check to handle tags refs is empty

 tags changes - Added check to handle tags refs is empty

---

webroot/js/coCharts/js/contrail-charts.js

Change-Id: If233bf32c94b122f35a90cb1c19e0bc9b43e15c0

Added deployment in Application Label

---

webroot/common/ui/scss/contrail.custom.scss
webroot/common/ui/templates/core.common.tmpl

Change-Id: Iea2a3d450d78cc0bc1e4de7c7b46c8832de08155

Displaying the policy rules in sidebar

---

webroot/js/models/ContrailConfigModel.js
webroot/js/views/tagsView.js

Change-Id: If9c8afa3dd6d4fc8b7e04be908c9b85d55926e25

  Tags separated with combo box based on tags type across all the pages

---

webroot/js/coCharts/css/contrail-charts.css

Change-Id: Ib84f641875019859a1491a0daf0514a2722aa8ea

Removed font family sans-serif

---

webroot/js/views/tagsView.js

Change-Id: I4175986a85a7afdc459a900295f62b8d6fdaef77

Filtering the tags for global and project level in the tabs tab.

---

webroot/common/ui/scss/contrail.custom.scss
webroot/common/ui/templates/core.common.tmpl
webroot/img/double_arrow.svg

Change-Id: I30bd16d48a6394f6c4fda8d92ea4eb33927e70fe

Monitoring page firewall rules related css in the side bar

---

webroot/common/ui/scss/contrail.chart.scss
webroot/common/ui/scss/contrail.custom.scss

Change-Id: Ice4532fd8b575b880dc10bbcf47e56bf1a75843e

Applying styles based on levels

---

webroot/js/coCharts/js/contrail-charts.js

Change-Id: I666eb0ff66814cef54c3dd6cda734b3990d87aad

Updated contrail-charts.js file

---

webroot/js/coCharts/js/contrail-charts.js

Change-Id: I199536150e4c534187ba3094bdfe9d7ef6effb74

Reverting the last link zero check commit.

---

webroot/js/views/GridView.js

Change-Id: Ic6720088d5d563e070892834595df3a8c23c8ce6

Implement intial filter in grid view

---

webroot/js/handlers/ContentHandler.js

on quickly jumping to "Traffic Groups" on expansion
Change-Id: I8b5ca3051bbbdb4476c08d09cda51ee159b2cf39

Fixed the loading issue that sometimes Networking > Dashboard is shown

---

webroot/common/ui/scss/contrail.chart.scss
webroot/common/ui/scss/contrail.custom.scss
webroot/common/ui/templates/core.common.tmpl
webroot/js/coCharts/js/contrail-charts.js

Change-Id: I2ddf1c29081535a1b1f28228dabfd29e4f322398

Added icons and legend section for labels

---

webroot/js/models/ContrailConfigModel.js

Change-Id: I09d81bf9ebec6e4987d150c2c8066ab7e98dcab7

Deleted unwanted fileds while saving in common place

---

webroot/common/ui/scss/contrail.chart.scss
webroot/common/ui/scss/contrail.custom.scss
webroot/common/ui/templates/core.common.tmpl
webroot/js/coCharts/js/contrail-charts.js
webroot/js/common/core.constants.js

Change-Id: I99661c9e3c8b800f6c6b1de17b5c12460cf65796

Updated charts-lib with latest changes     Implemented Refresh and Reset stats functionality

---

webroot/common/ui/scss/contrail.custom.scss
webroot/common/ui/templates/core.common.tmpl

On click of stats icon, showing endpoints details in the grid
Change-Id: I7cac32d38a621110f73ff73f651c59e2b50ef7e2

Added endpoint stats icon in link info section

---

webroot/common/ui/scss/contrail.custom.scss
webroot/js/common/core.constants.js

Change-Id: I76790b54384e266749bb2793bfab156e1e31e777

Added tabs for each endpoint in stats grid

---

webroot/common/ui/scss/contrail.custom.scss
webroot/common/ui/templates/core.common.tmpl

Change-Id: Ib3ca6b4a9ebcfbe6406eefbdf1c0a784a9dcfb5f

Implemented filter by multiple endpoints

---

webroot/common/ui/scss/contrail.custom.scss
webroot/common/ui/templates/core.common.tmpl

Change-Id: I6e2ae5d4d7573c15a9b5ac201ff28a7c82b2f0fe

Added the gridview for endpoint stats.
